"""Restore required fields to cycle_counts

Revision ID: 110c7d49312d
Revises: 95ce3ee9c0c1
Create Date: 2026-03-19 15:43:29.829413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '110c7d49312d'
down_revision: Union[str, Sequence[str], None] = '95ce3ee9c0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bin_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('abc_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.alter_column('import_reference',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('waybill',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.alter_column('waybill',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('import_reference',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_column('abc_code')
        batch_op.drop_column('username')
        batch_op.drop_column('bin_location')
        batch_op.drop_column('item_description')

    # ### end Alembic commands ###
