"""add_inbound_alerts_table

Revision ID: 226661b888ff
Revises: 9ff04b3ff0e3
Create Date: 2026-07-06 20:24:09.319576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '226661b888ff'
down_revision: Union[str, Sequence[str], None] = '9ff04b3ff0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('import_reference', sa.String(length=100), nullable=False),
    sa.Column('waybill', sa.String(length=100), nullable=True),
    sa.Column('grn', sa.String(length=100), nullable=False),
    sa.Column('qty_expected', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('financial_impact', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('draft_claim_email', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.String(length=50), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_alerts_alert_id'), ['alert_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_inbound_alerts_grn'), ['grn'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_alerts_import_reference'), ['import_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_alerts_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_alerts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_inbound_alerts_item_code'))
        batch_op.drop_index(batch_op.f('ix_inbound_alerts_import_reference'))
        batch_op.drop_index(batch_op.f('ix_inbound_alerts_grn'))
        batch_op.drop_index(batch_op.f('ix_inbound_alerts_alert_id'))

    op.drop_table('inbound_alerts')
    # ### end Alembic commands ###
