"""fix_missing_columns_master_items

Revision ID: 2a6fa80d5f09
Revises: 3af302cd24be
Create Date: 2026-03-23 19:46:11.815722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2a6fa80d5f09'
down_revision: Union[str, Sequence[str], None] = '3af302cd24be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_count_recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planned_date', sa.String(length=50), nullable=False),
    sa.Column('executed_date', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('bin_location', sa.String(length=100), nullable=True),
    sa.Column('system_qty', sa.Integer(), nullable=False),
    sa.Column('physical_qty', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('abc_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_count_recordings_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('count_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stock_counts', ['count_id'], ['id'])
        batch_op.drop_column('executed_date')
        batch_op.drop_column('planned_date')
        batch_op.drop_column('difference')
        batch_op.drop_column('physical_qty')
        batch_op.drop_column('item_description')
        batch_op.drop_column('username')
        batch_op.drop_column('bin_location')
        batch_op.drop_column('system_qty')

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lines', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('aaf_grn1', sa.Numeric(precision=10, scale=5), nullable=True))
        batch_op.add_column(sa.Column('grn3_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ct', sa.String(length=50), nullable=True))

    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sic_code_company', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sic_code_stockroom', sa.String(length=50), nullable=True))

    with op.batch_alter_table('reconciliation_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_reference', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('waybill', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('grn', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('bin_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('relocated_bin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reconciliation_history', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('relocated_bin')
        batch_op.drop_column('bin_location')
        batch_op.drop_column('description')
        batch_op.drop_column('grn')
        batch_op.drop_column('waybill')
        batch_op.drop_column('import_reference')

    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.drop_column('sic_code_stockroom')
        batch_op.drop_column('sic_code_company')

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_column('ct')
        batch_op.drop_column('grn3_date')
        batch_op.drop_column('aaf_grn1')
        batch_op.drop_column('lines')

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('bin_location', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('item_description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('physical_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('difference', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planned_date', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('executed_date', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('count_id')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_item_code'))

    op.drop_table('cycle_count_recordings')
    # ### end Alembic commands ###
