"""change_level_to_string

Revision ID: 2c4ce1fdc699
Revises: fbb9ff6fda24
Create Date: 2026-04-23 17:34:02.724012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c4ce1fdc699'
down_revision: Union[str, Sequence[str], None] = 'fbb9ff6fda24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bin_locations', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_nullable=False)





    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###




    with op.batch_alter_table('bin_locations', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
