"""Add ai_item_patterns table

Revision ID: 3af302cd24be
Revises: cbf611641dc0
Create Date: 2026-03-22 13:49:21.258626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af302cd24be'
down_revision: Union[str, Sequence[str], None] = 'cbf611641dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_category_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sic_code', sa.String(length=100), nullable=False),
    sa.Column('bin_code', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_category_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_category_patterns_sic_code'), ['sic_code'], unique=False)

    op.create_table('ai_item_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('bin_code', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_item_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_item_patterns_item_code'), ['item_code'], unique=False)





    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###




    with op.batch_alter_table('ai_item_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_item_patterns_item_code'))

    op.drop_table('ai_item_patterns')
    with op.batch_alter_table('ai_category_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_category_patterns_sic_code'))

    op.drop_table('ai_category_patterns')
    # ### end Alembic commands ###
