"""add client_id to logs table

Revision ID: 3e48d4728c75
Revises: 3af302cd24be
Create Date: 2026-03-29 15:43:41.403767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e48d4728c75'
down_revision: Union[str, Sequence[str], None] = '3af302cd24be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_logs_client_id'), ['client_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_client_id'))
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
