"""add_ir_reconciliations_table

Revision ID: 461f8f05b05c
Revises: 226661b888ff
Create Date: 2026-07-06 20:30:22.939080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461f8f05b05c'
down_revision: Union[str, Sequence[str], None] = '226661b888ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ir_reconciliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('import_reference', sa.String(length=100), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('completed_lines', sa.Integer(), nullable=False),
    sa.Column('started_lines', sa.Integer(), nullable=False),
    sa.Column('expected_units', sa.Integer(), nullable=False),
    sa.Column('received_units', sa.Integer(), nullable=False),
    sa.Column('ok_lines', sa.Integer(), nullable=False),
    sa.Column('negative_diff_lines', sa.Integer(), nullable=False),
    sa.Column('positive_diff_lines', sa.Integer(), nullable=False),
    sa.Column('total_grns', sa.Integer(), nullable=False),
    sa.Column('completed_grns', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ir_reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ir_reconciliations_import_reference'), ['import_reference'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ir_reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ir_reconciliations_import_reference'))

    op.drop_table('ir_reconciliations')
    # ### end Alembic commands ###
