"""create_master_items_table

Revision ID: 48de25da08cc
Revises: 857f4abe9bac
Create Date: 2026-02-07 17:32:49.179436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48de25da08cc'
down_revision: Union[str, Sequence[str], None] = '857f4abe9bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.alter_column('system_qty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('difference',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)


    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_cycle_counts_stock_counts', 'stock_counts', ['count_id'], ['id'])

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_picking_package_items_picking_audits', 'picking_audits', ['audit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cycle_counts_ibfk_1'), 'stock_counts', ['count_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_cycle_counts_item_code'))
        batch_op.create_index(batch_op.f('idx_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_item_code'))
        batch_op.create_index(batch_op.f('idx_ccr_item_code'), ['item_code'], unique=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('difference',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('system_qty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###

    # ### end Alembic commands ###
