"""create_master_items_table

Revision ID: 48de25da08cc
Revises: 857f4abe9bac
Create Date: 2026-02-07 17:32:49.179436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48de25da08cc'
down_revision: Union[str, Sequence[str], None] = '857f4abe9bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_count_recordings_backup_20260202', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_item_code'))

    op.drop_table('cycle_count_recordings_backup_20260202')
    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.alter_column('system_qty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('difference',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_ccr_item_code'))
        batch_op.create_index(batch_op.f('ix_cycle_count_recordings_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_item_code'))
        batch_op.create_index(batch_op.f('ix_cycle_counts_item_code'), ['item_code'], unique=False)
        batch_op.drop_constraint(batch_op.f('cycle_counts_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stock_counts', ['count_id'], ['id'])

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'picking_audits', ['audit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cycle_counts_ibfk_1'), 'stock_counts', ['count_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_cycle_counts_item_code'))
        batch_op.create_index(batch_op.f('idx_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_item_code'))
        batch_op.create_index(batch_op.f('idx_ccr_item_code'), ['item_code'], unique=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('difference',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('system_qty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.create_table('cycle_count_recordings_backup_20260202',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('original_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('planned_date', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('executed_date', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('item_code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('item_description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('bin_location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('system_qty', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('physical_qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('difference', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('abc_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('backup_timestamp', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cycle_count_recordings_backup_20260202', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_item_code'), ['item_code'], unique=False)

    # ### end Alembic commands ###
