"""Add GRNMaster table

Revision ID: 5bb7d61e7826
Revises: dd6399c6090e
Create Date: 2026-02-07 23:47:31.886156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5bb7d61e7826'
down_revision: Union[str, Sequence[str], None] = 'dd6399c6090e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grn_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_reference', sa.String(length=100), nullable=False),
    sa.Column('waybill', sa.String(length=100), nullable=False),
    sa.Column('grn_number', sa.String(length=255), nullable=True),
    sa.Column('packs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lines', sa.String(length=50), nullable=True),
    sa.Column('aaf_date', sa.String(length=50), nullable=True),
    sa.Column('grn1_date', sa.String(length=50), nullable=True),
    sa.Column('aaf_grn1', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('grn3_date', sa.String(length=50), nullable=True),
    sa.Column('grn1_grn3', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('ct', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grn_master_import_reference'), ['import_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_master_waybill'), ['waybill'], unique=False)

    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.alter_column('item_code',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('physical_qty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('bin_1',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('additional_bin',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('weight_per_unit',
               existing_type=mysql.DECIMAL(precision=10, scale=3),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_master_items_abc_code'), ['abc_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_items_bin_1'), ['bin_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_items_item_code'), ['item_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_items_item_code'))
        batch_op.drop_index(batch_op.f('ix_master_items_bin_1'))
        batch_op.drop_index(batch_op.f('ix_master_items_abc_code'))
        batch_op.alter_column('updated_at',
               existing_type=sa.String(length=50),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('weight_per_unit',
               existing_type=sa.String(length=50),
               type_=mysql.DECIMAL(precision=10, scale=3),
               existing_nullable=True)
        batch_op.alter_column('additional_bin',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('bin_1',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('physical_qty',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('item_code',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_master_waybill'))
        batch_op.drop_index(batch_op.f('ix_grn_master_import_reference'))

    op.drop_table('grn_master')
    # ### end Alembic commands ###
