"""Apply logix_react implementations

Revision ID: 6029e08e4844
Revises: 54875259d469
Create Date: 2026-05-16 11:47:55.151635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6029e08e4844'
down_revision: Union[str, Sequence[str], None] = '54875259d469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bin_location', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spot_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spot_checks_bin_location'), ['bin_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_spot_checks_item_code'), ['item_code'], unique=False)

    op.create_table('picking_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('package_number', sa.Integer(), nullable=False),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('width', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['picking_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picking_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picking_packages_audit_id'), ['audit_id'], unique=False)

    pass
    with op.batch_alter_table('bin_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('count_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.alter_column('item_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('abc_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_index(batch_op.f('ix_cycle_counts_item_code'), ['item_code'], unique=False)
        batch_op.create_foreign_key('fk_cycle_counts_stock_counts', 'stock_counts', ['count_id'], ['id'])

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.alter_column('import_reference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('waybill',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('lines',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('aaf_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn1_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn3_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('ct',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_grn_master_import_reference'), ['import_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_master_waybill'), ['waybill'], unique=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('importReference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('waybill',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('itemCode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('itemDescription',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('binLocation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('relocatedBin',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('archived_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))

    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frozen_qty', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.drop_column('frozen_qty')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('archived_at',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('relocatedBin',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('binLocation',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('itemDescription',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('itemCode',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('waybill',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('importReference',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_master_waybill'))
        batch_op.drop_index(batch_op.f('ix_grn_master_import_reference'))
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('ct',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn3_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn1_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('aaf_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('lines',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('waybill',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('import_reference',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cycle_counts_item_code'))
        batch_op.alter_column('abc_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('item_code',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('count_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('bin_locations', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('score')

    op.create_table('_alembic_tmp_count_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=50), nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=50), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('inventory_stage', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planner_holidays',
    sa.Column('date', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('picking_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_packages_audit_id'))

    op.drop_table('picking_packages')
    with op.batch_alter_table('spot_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spot_checks_item_code'))
        batch_op.drop_index(batch_op.f('ix_spot_checks_bin_location'))

    op.drop_table('spot_checks')
    # ### end Alembic commands ###
