"""add_cycle_counts_table

Revision ID: 6cadaae25e57
Revises: add_package_items
Create Date: 2025-12-28 21:55:23.019838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cadaae25e57'
down_revision: Union[str, Sequence[str], None] = 'add_package_items'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('abc_code', sa.String(length=10), nullable=True),
    sa.Column('count_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['count_id'], ['stock_counts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_counts_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_importReference_itemCode'))
        batch_op.drop_column('observaciones')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_password_reset_token'))

    with op.batch_alter_table('picking_audit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_picking_audit_id'))

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_package_items_audit_id'))
        batch_op.create_index(batch_op.f('ix_picking_package_items_audit_id'), ['audit_id'], unique=False)

    with op.batch_alter_table('recount_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_recount_item_stage'))

    with op.batch_alter_table('session_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_location_code'))

    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_session_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('session_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_location_code'), ['location_code'], unique=False)

    with op.batch_alter_table('recount_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_recount_item_stage'), ['item_code', 'stage_to_count'], unique=False)

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_package_items_audit_id'))
        batch_op.create_index(batch_op.f('idx_package_items_audit_id'), ['audit_id'], unique=False)

    with op.batch_alter_table('picking_audit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_picking_audit_id'), ['audit_id'], unique=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_password_reset_token'), ['token'], unique=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.VARCHAR(length=500), nullable=True))
        batch_op.create_index(batch_op.f('idx_importReference_itemCode'), ['importReference', 'itemCode'], unique=False)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_counts_item_code'))

    op.drop_table('cycle_counts')
    # ### end Alembic commands ###
