"""add_customer_code_to_picking_audit

Revision ID: 8f1125eae21a
Revises: 475017242a53
Create Date: 2026-03-13 14:25:11.210623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1125eae21a'
down_revision: Union[str, Sequence[str], None] = '475017242a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picking_audits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_package_items_audit_id'))
        batch_op.create_index(batch_op.f('ix_picking_package_items_audit_id'), ['audit_id'], unique=False)

    with op.batch_alter_table('shipment_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_id'))
        batch_op.drop_index(batch_op.f('idx_shipment_id'))
        batch_op.create_index(batch_op.f('ix_shipment_audits_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_audits_shipment_id'), ['shipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_audits_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_audits_audit_id'))
        batch_op.create_index(batch_op.f('idx_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_audit_id'), ['audit_id'], unique=False)

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_package_items_audit_id'))
        batch_op.create_index(batch_op.f('idx_package_items_audit_id'), ['audit_id'], unique=False)

    with op.batch_alter_table('picking_audits', schema=None) as batch_op:
        batch_op.drop_column('customer_code')

    # ### end Alembic commands ###
