"""add frozen_qty to master_items

Revision ID: 9ff04b3ff0e3
Revises: 062da92f6d9b
Create Date: 2026-05-14 19:57:40.072774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff04b3ff0e3'
down_revision: Union[str, Sequence[str], None] = '062da92f6d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # El resto de los comandos autogenerados eran redundantes y causaban errores de duplicado
    # Mantenemos solo el cambio real: agregar frozen_qty a master_items
    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frozen_qty', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.drop_column('frozen_qty')

    # ### end Alembic commands ###
