"""add frozen_qty to master_items

Revision ID: 9ff04b3ff0e3
Revises: 062da92f6d9b
Create Date: 2026-05-14 19:57:40.072774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff04b3ff0e3'
down_revision: Union[str, Sequence[str], None] = '062da92f6d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manejar tablas con nombres temporales si existen (limpieza de fallos previos)
    # op.drop_table('_alembic_tmp_ai_category_patterns') # Comentado porque puede fallar si no existe
    
    with op.batch_alter_table('ai_category_patterns', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_ai_category_patterns_sic_code'), ['sic_code'], unique=False)

    with op.batch_alter_table('ai_item_patterns', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_ai_item_patterns_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('count_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_cycle_count_recordings_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_cycle_counts_item_code'), ['item_code'], unique=False)
        batch_op.create_foreign_key('fk_cycle_counts_stock_counts', 'stock_counts', ['count_id'], ['id'])

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_grn_master_import_reference'), ['import_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_master_waybill'), ['waybill'], unique=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_logs_client_id'), ['client_id'], unique=True)

    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frozen_qty', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_master_items_abc_code'), ['abc_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_items_bin_1'), ['bin_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_items_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_foreign_key('fk_password_reset_tokens_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('picking_audit_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_picking_audit_items_audit_id'), ['audit_id'], unique=False)
        batch_op.create_foreign_key('fk_picking_audit_items_picking_audits', 'picking_audits', ['audit_id'], ['id'])

    with op.batch_alter_table('picking_audits', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_picking_package_items_audit_id'), ['audit_id'], unique=False)
        batch_op.create_foreign_key('fk_picking_package_items_picking_audits', 'picking_audits', ['audit_id'], ['id'])

    with op.batch_alter_table('reconciliation_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_reconciliation_history_archive_date'), ['archive_date'], unique=False)

    with op.batch_alter_table('recount_list', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('session_locations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_session_locations_location_code'), ['location_code'], unique=False)
        batch_op.create_foreign_key('fk_session_locations_count_sessions', 'count_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('shipment_audits', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_shipment_audits_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_audits_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_foreign_key('fk_shipment_audits_shipments', 'shipments', ['shipment_id'], ['id'])
        batch_op.create_foreign_key('fk_shipment_audits_picking_audits', 'picking_audits', ['audit_id'], ['id'])

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_stock_counts_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key('fk_stock_counts_count_sessions', 'count_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stock_counts_count_sessions', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_stock_counts_session_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('shipment_audits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shipment_audits_picking_audits', type_='foreignkey')
        batch_op.drop_constraint('fk_shipment_audits_shipments', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_shipment_audits_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_audits_audit_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('session_locations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_session_locations_count_sessions', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_session_locations_location_code'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('recount_list', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('reconciliation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_history_archive_date'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_picking_package_items_picking_audits', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_picking_package_items_audit_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('picking_audits', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('picking_audit_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_picking_audit_items_picking_audits', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_picking_audit_items_audit_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_password_reset_tokens_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_items_item_code'))
        batch_op.drop_index(batch_op.f('ix_master_items_bin_1'))
        batch_op.drop_index(batch_op.f('ix_master_items_abc_code'))
        batch_op.drop_column('frozen_qty')

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_client_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_master_waybill'))
        batch_op.drop_index(batch_op.f('ix_grn_master_import_reference'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cycle_counts_stock_counts', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cycle_counts_item_code'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_item_code'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('count_sessions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ai_item_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_item_patterns_item_code'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ai_category_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_category_patterns_sic_code'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
