"""restore missing cycle_count_recordings table

Revision ID: a1e675b2b9dd
Revises: c03712f69631
Create Date: 2026-01-11 16:49:20.599263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e675b2b9dd'
down_revision: Union[str, Sequence[str], None] = 'c03712f69631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_count_recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planned_date', sa.String(length=50), nullable=False),
    sa.Column('executed_date', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('bin_location', sa.String(length=100), nullable=True),
    sa.Column('system_qty', sa.Integer(), nullable=False),
    sa.Column('physical_qty', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('abc_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_count_recordings_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_package_items_audit_id'))
        batch_op.create_index(batch_op.f('ix_picking_package_items_audit_id'), ['audit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_package_items_audit_id'))
        batch_op.create_index(batch_op.f('idx_package_items_audit_id'), ['audit_id'], unique=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_item_code'))

    op.drop_table('cycle_count_recordings')
    # ### end Alembic commands ###
