"""initial_migration

Revision ID: c03712f69631
Revises: 
Create Date: 2026-01-09 22:30:35.275407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03712f69631'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('count_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('inventory_stage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycle_count_recordings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planned_date', sa.String(length=50), nullable=False),
    sa.Column('executed_date', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('bin_location', sa.String(length=100), nullable=True),
    sa.Column('system_qty', sa.Integer(), nullable=False),
    sa.Column('physical_qty', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('abc_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_count_recordings_item_code'), ['item_code'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('importReference', sa.String(length=100), nullable=False),
    sa.Column('waybill', sa.String(length=100), nullable=True),
    sa.Column('itemCode', sa.String(length=100), nullable=True),
    sa.Column('itemDescription', sa.String(length=255), nullable=True),
    sa.Column('binLocation', sa.String(length=100), nullable=True),
    sa.Column('relocatedBin', sa.String(length=100), nullable=True),
    sa.Column('qtyReceived', sa.Integer(), nullable=True),
    sa.Column('qtyGrn', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picking_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('despatch_number', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('packages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recount_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('stage_to_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_approved', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)

    op.create_table('picking_audit_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('order_line', sa.String(length=50), nullable=True),
    sa.Column('qty_req', sa.Integer(), nullable=False),
    sa.Column('qty_scan', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['picking_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picking_audit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picking_audit_items_audit_id'), ['audit_id'], unique=False)

    op.create_table('picking_package_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('package_number', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('qty_scan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['picking_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picking_package_items_audit_id'), ['audit_id'], unique=False)

    op.create_table('session_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('closed_at', sa.String(length=50), nullable=True),
    sa.Column('count_stage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['count_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_locations_location_code'), ['location_code'], unique=False)

    op.create_table('stock_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('item_description', sa.String(length=255), nullable=True),
    sa.Column('counted_qty', sa.Integer(), nullable=False),
    sa.Column('counted_location', sa.String(length=100), nullable=False),
    sa.Column('bin_location_system', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['count_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_counts_session_id'), ['session_id'], unique=False)

    op.create_table('cycle_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('abc_code', sa.String(length=10), nullable=True),
    sa.Column('count_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['count_id'], ['stock_counts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cycle_counts_item_code'), ['item_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_counts_item_code'))

    op.drop_table('cycle_counts')
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_counts_session_id'))

    op.drop_table('stock_counts')
    with op.batch_alter_table('session_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_locations_location_code'))

    op.drop_table('session_locations')
    with op.batch_alter_table('picking_package_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_package_items_audit_id'))

    op.drop_table('picking_package_items')
    with op.batch_alter_table('picking_audit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picking_audit_items_audit_id'))

    op.drop_table('picking_audit_items')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    op.drop_table('recount_list')
    op.drop_table('picking_audits')
    op.drop_table('logs')
    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_item_code'))

    op.drop_table('cycle_count_recordings')
    op.drop_table('count_sessions')
    op.drop_table('app_state')
    # ### end Alembic commands ###
