"""add_w2w_inventory_snapshots_table

Revision ID: d81f26fc1cc4
Revises: 461f8f05b05c
Create Date: 2026-08-07 20:49:29.879788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_w2w_inventory_snapshots_table

Revision ID: d81f26fc1cc4
Revises: 461f8f05b05c
Create Date: 2026-08-07 20:49:29.879788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81f26fc1cc4'
down_revision: Union[str, Sequence[str], None] = '461f8f05b05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'w2w_inventory_snapshots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('item_code', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('bin_location', sa.String(length=100), nullable=True),
        sa.Column('system_qty', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('unit_cost', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('created_at', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['count_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_w2w_inventory_snapshots_item_code'), 'w2w_inventory_snapshots', ['item_code'], unique=False)
    op.create_index(op.f('ix_w2w_inventory_snapshots_session_id'), 'w2w_inventory_snapshots', ['session_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_w2w_inventory_snapshots_session_id'), table_name='w2w_inventory_snapshots')
    op.drop_index(op.f('ix_w2w_inventory_snapshots_item_code'), table_name='w2w_inventory_snapshots')
    op.drop_table('w2w_inventory_snapshots')
