"""add grn columns to ir_reconciliations

Revision ID: eff7237529dc
Revises: 8c2b6f678756
Create Date: 2026-07-02 20:39:20.551474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff7237529dc'
down_revision: Union[str, Sequence[str], None] = '8c2b6f678756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ir_reconciliations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_grns', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('completed_grns', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ir_reconciliations', schema=None) as batch_op:
        batch_op.drop_column('completed_grns')
        batch_op.drop_column('total_grns')

    # ### end Alembic commands ###
