"""add reconciliation history table

Revision ID: fc5f66738c8e
Revises: 2129456be612
Create Date: 2026-03-07 09:47:26.475615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5f66738c8e'
down_revision: Union[str, Sequence[str], None] = '2129456be612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_date', sa.String(length=50), nullable=False),
    sa.Column('import_reference', sa.String(length=100), nullable=False),
    sa.Column('waybill', sa.String(length=100), nullable=False),
    sa.Column('grn', sa.String(length=100), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('qty_expected', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_history_archive_date'), ['archive_date'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('carrier', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['picking_audits.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_audits_audit_id'), ['audit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_audits_shipment_id'), ['shipment_id'], unique=False)

    with op.batch_alter_table('count_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.alter_column('planned_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('executed_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('item_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('item_description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('bin_location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('abc_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_index(batch_op.f('ix_cycle_count_recordings_item_code'), ['item_code'], unique=False)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.alter_column('item_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('abc_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.create_index(batch_op.f('ix_cycle_counts_item_code'), ['item_code'], unique=False)
        batch_op.create_foreign_key(None, 'stock_counts', ['count_id'], ['id'])

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.alter_column('import_reference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('waybill',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('grn_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('lines',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('aaf_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn1_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn3_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('ct',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_grn_master_import_reference'), ['import_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_grn_master_waybill'), ['waybill'], unique=False)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('importReference',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('waybill',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('itemCode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('itemDescription',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('binLocation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('relocatedBin',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('archived_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('archived_at',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('relocatedBin',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('binLocation',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('itemDescription',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('itemCode',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('waybill',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('importReference',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('grn_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grn_master_waybill'))
        batch_op.drop_index(batch_op.f('ix_grn_master_import_reference'))
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('ct',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn3_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn1_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('aaf_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('lines',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('grn_number',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('waybill',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('import_reference',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('cycle_counts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cycle_counts_item_code'))
        batch_op.alter_column('abc_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('timestamp',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('item_code',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('cycle_count_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cycle_count_recordings_item_code'))
        batch_op.alter_column('abc_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('bin_location',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('item_description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('item_code',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('executed_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('planned_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('count_sessions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
        batch_op.alter_column('start_time',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('user_username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('shipment_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_audits_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_audits_audit_id'))

    op.drop_table('shipment_audits')
    op.drop_table('shipments')
    with op.batch_alter_table('reconciliation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_history_archive_date'))

    op.drop_table('reconciliation_history')
    # ### end Alembic commands ###
